import { mkdir, writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';
import { publicSongs } from '../data/song-library.mjs';

export const STUDIO_VERSION = '20261001.1';
const esc = (v = '') => String(v).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
export function studioNav(locale = 'zh', active = 'piano') {
  const zh = locale === 'zh', base = zh ? '' : '/en';
  const destination = active === 'songs' ? '/songs/' : active === 'learn' ? '/tutorials.html' : '/piano.html';
  return `<nav class="nav-bar" aria-label="${zh ? '主导航' : 'Main navigation'}"><div class="nav-container"><a class="studio-brand" href="${base}/" aria-label="Piano Online"><span class="brand-keys" aria-hidden="true"><i></i><i></i><i></i></span><span>Piano<span class="brand-light">Online</span><small>${zh ? '让音乐发生' : 'MAKE A LITTLE MUSIC'}</small></span></a><div class="nav-links"><a href="${base}/piano.html"${active === 'piano' ? ' class="active" aria-current="page"' : ''}>${zh ? '弹钢琴' : 'Piano'}</a><a href="${base}/songs/"${active === 'songs' ? ' class="active" aria-current="page"' : ''}>${zh ? '找首歌' : 'Songs'}</a><a href="${base}/tutorials.html"${active === 'learn' ? ' class="active" aria-current="page"' : ''}>${zh ? '学一点' : 'Learn'}</a><a class="studio-language" href="${zh ? '/en' + destination : destination}" lang="${zh ? 'en' : 'zh-CN'}">${zh ? 'EN' : '中文'}</a></div></div></nav>`;
}

export function studioInstrument(locale = 'zh', songId = 'happy-birthday') {
  const zh = locale === 'zh', s = (a, b) => zh ? a : b;
  const options = publicSongs.map(song => `<option value="${esc(song.id)}"${song.id === songId ? ' selected' : ''}>${esc(song.title[locale])}</option>`).join('');
  return `<section id="practice-start" class="practice-section studio-instrument song-practice-shell" tabindex="-1" aria-label="${s('在线钢琴', 'Interactive piano')}" data-studio>
  <div class="studio-toolbar"><div class="studio-modes" role="group" aria-label="${s('演奏模式', 'Playing mode')}"><button type="button" data-play-mode="free" aria-pressed="true">${s('自由弹奏', 'Free play')}</button><button type="button" data-play-mode="guided" aria-pressed="false">${s('跟着提示弹', 'Learn a song')}</button></div><button type="button" id="toggle-fullscreen" class="studio-quiet" aria-pressed="false"><span aria-hidden="true">⛶</span> <span data-fullscreen-label>${s('专注全屏', 'Full screen')}</span></button></div>
  <div class="studio-song-bar" id="studio-song-bar" hidden><label for="song-select">${s('选择歌曲', 'Choose a song')}</label><select id="song-select">${options}</select><button type="button" id="start-practice" class="studio-primary" disabled>${s('开始跟弹', 'Start learning')}</button><button type="button" id="stop-practice" class="studio-primary" style="display:none">${s('停止练习', 'Stop practice')}</button><a href="${zh ? '/songs/' : '/en/songs/'}">${s('浏览曲库', 'Browse songs')} ↗</a></div>
  <div class="studio-surface"><div class="studio-display"><div class="studio-display-copy"><span class="studio-eyebrow">PIANO ONLINE <span class="studio-dot"></span></span><h2 id="studio-message">${s('随手按下一个音符。', 'Make yourself a little music.')}</h2><p id="studio-submessage">${s('点击琴键，或按电脑键盘上的 A、S、D。', 'Click a key, or press A, S, D on your keyboard.')}</p></div><div class="studio-readout"><span id="studio-note">—</span><small id="studio-note-caption">${s('当前音符', 'CURRENT NOTE')}</small></div><div id="key-hint" class="key-hint" style="display:none"><span class="hint-text">${s('下一键', 'NEXT KEY')}</span><span class="hint-key"></span><span class="hint-note"></span></div></div>
  <div id="studio-upcoming" class="studio-upcoming" aria-label="${s('接下来的音符', 'Upcoming notes')}" hidden></div>
  <div id="practice-stats" class="studio-progress" style="display:none"><span id="correct-notes"></span><span id="wrong-notes"></span><span id="progress"></span><progress id="studio-progressbar" max="100" value="0" aria-label="${s('练习进度', 'Practice progress')}"></progress></div>
  <div id="note-drop-zone" class="note-drop-zone" style="display:none"><div id="falling-notes" class="falling-notes"></div></div>
  <div class="studio-keyboard-viewport" id="keyboard-viewport"><div class="piano-container"><div class="keys" role="group" aria-label="${s('37 个琴键，C3 到 C6', '37 piano keys, C3 to C6')}"></div></div></div>
  <div class="studio-range"><button type="button" data-octave="-1" aria-label="${s('向低音区移动', 'Move to lower notes')}">← <span>${s('低音', 'Lower')}</span></button><span>${s('37 键 · C3—C6', '37 keys · C3—C6')}<span class="mobile-only"> · ${s('用两侧箭头切换音区', 'Use arrows to change range')}</span></span><button type="button" data-octave="1" aria-label="${s('向高音区移动', 'Move to higher notes')}"><span>${s('高音', 'Higher')}</span> →</button></div></div>
  <div class="studio-bottom"><div class="studio-settings"><label class="studio-volume" for="studio-volume"><span aria-hidden="true">◖))</span><span class="sr-only">${s('音量', 'Volume')}</span><input id="studio-volume" type="range" min="0" max="100" value="62"><output for="studio-volume" id="studio-volume-value">62%</output></label><label class="studio-toggle"><input type="checkbox" id="sustain-toggle">${s('延音', 'Sustain')}</label><label class="studio-toggle"><input type="checkbox" id="labels-toggle" checked>${s('字母提示', 'Key labels')}</label></div><span id="studio-audio-status" role="status">${s('按下琴键开启声音', 'Press a key to enable sound')}</span></div>
  <details class="studio-more"><summary>${s('更多工具与快捷键', 'More tools & keyboard help')}</summary><div class="studio-more-content"><p>${s('字母是电脑按键，小字是实际音名。按住空格键可临时延音；松开即恢复。手机上用两侧箭头切换音区。', 'Large letters are computer keys; small labels are musical notes. Hold Space for sustain. On mobile, use the arrows to change the visible range.')}</p><button type="button" id="studio-midi" class="studio-quiet">${s('连接 MIDI 键盘', 'Connect a MIDI keyboard')}</button><span id="studio-midi-status" role="status"></span><div class="studio-rhythm-tools"><button type="button" id="start-rhythm-game" class="studio-quiet">${s('节奏模式', 'Rhythm mode')}</button><button type="button" id="stop-rhythm-game" class="studio-quiet" style="display:none">${s('结束节奏模式', 'Stop rhythm mode')}</button><div id="game-instructions" style="display:none">${s('音符到达底部时，按对应的电脑按键。', 'Press the matching computer key when a note reaches the bottom.')}</div><div id="game-stats" style="display:none"><span id="game-score">0</span> · <span id="game-combo">0</span> · <span id="game-lives">3</span></div></div><a href="${zh ? '/practice.html' : '/en/tutorials.html'}">${s('音阶、和弦与节拍练习', 'Scales, chords & rhythm practice')} ↗</a></div></details>
  <p class="studio-error" id="studio-error" role="alert" hidden></p><noscript><p>${s('请开启 JavaScript 来弹奏。歌曲的按键谱仍可在曲库中阅读。', 'Enable JavaScript to play. You can still read the keyboard letters in the song library.')}</p></noscript></section>`;
}

export function renderStudioPage(locale = 'zh', home = true) {
  const zh = locale === 'zh', s = (a,b) => zh ? a : b, base = zh ? '' : '/en';
  const url = `https://pianoonline.cc${base}/${home ? '' : 'piano.html'}`;
  const alternate = `https://pianoonline.cc${zh ? '/en' : ''}/${home ? '' : 'piano.html'}`;
  const title = s('在线钢琴 · 打开就能弹，跟着提示学歌 | Piano Online', 'Online Piano · Play instantly & learn a song | Piano Online');
  const description = s('免费的在线钢琴，支持鼠标、触屏和电脑键盘。37 个琴键、逐键学歌提示、音量与延音控制，无需注册。', 'Play a free online piano with your keyboard, mouse or touchscreen. 37 keys, guided songs, volume, sustain and distraction-free full screen. No signup.');
  const featured = ['happy-birthday','twinkle','ode-to-joy','jingle-bells','fur-elise','canon'].map(id=>publicSongs.find(x=>x.id===id)).filter(Boolean);
  return `<!DOCTYPE html><html lang="${zh ? 'zh-CN' : 'en'}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><link rel="canonical" href="${url}"><link rel="alternate" hreflang="${zh ? 'zh-CN' : 'en'}" href="${url}"><link rel="alternate" hreflang="${zh ? 'en' : 'zh-CN'}" href="${alternate}"><link rel="alternate" hreflang="x-default" href="${zh ? alternate : url}"><link rel="icon" href="/images/favicon.svg"><meta property="og:type" content="website"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${url}"><meta property="og:image" content="https://pianoonline.cc/images/og-image.jpg"><link rel="stylesheet" href="/css/studio.css?v=${STUDIO_VERSION}"><script type="module" src="/js/studio.js?v=${STUDIO_VERSION}"></script><script async src="https://www.googletagmanager.com/gtag/js?id=G-EYGD99YB4Y"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','G-EYGD99YB4Y');</script><meta name="google-site-verification" content="Fii3zK2l54f0uFP7RPwdn7BEqB4OjC2jc_07JxSs1uI">${home ? '<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4423187689700927" crossorigin="anonymous"></script>' : ''}</head>
<body class="studio-page"><a class="skip-link" href="#practice-start">${s('跳到钢琴', 'Skip to piano')}</a>${studioNav(locale)}<main class="studio-main"><header class="studio-intro"><div><p class="studio-kicker">${s('一点空闲，一段旋律', 'A LITTLE TIME. A LITTLE MUSIC.')}</p><h1>${s('在线钢琴，打开就能弹。', 'Your piano. Whenever inspiration strikes.')}</h1><p>${s('随心弹一段，或跟着亮起的琴键学会一首歌。', 'Play something of your own, or follow the keys to learn a familiar song.')}</p></div><div class="studio-promise"><span>${s('免费', 'Free')}</span><span>${s('无需注册', 'No signup')}</span><span>${s('手机也能弹', 'Touch friendly')}</span></div></header>${studioInstrument(locale)}
<section class="studio-discover"><div class="studio-section-heading"><div><p class="studio-kicker">${s('从熟悉的旋律开始', 'FIND YOUR FIRST MELODY')}</p><h2>${s('今天，想弹哪一首？', 'What would you like to play?')}</h2></div><a href="${base}/songs/">${s(`全部 ${publicSongs.length} 首歌曲`, `All ${publicSongs.length} songs`)} →</a></div><div class="studio-song-grid">${featured.map((song,i)=>`<a class="studio-song-card" href="${base}/songs/${song.slug}/"><span class="studio-song-art" data-art="${i}"><span aria-hidden="true">${['♪','✧','♩','❋','♬','𝄞'][i]}</span><small>0${i+1}</small></span><span class="studio-song-copy"><small>${s(['入门','简单','中等','进阶'][Math.min(3,song.difficulty-1)],['Starter','Easy','Medium','Advanced'][Math.min(3,song.difficulty-1)])} · ${song.estimatedMinutes} ${s('分钟','min')}</small><strong>${esc(song.title[locale])}</strong><span>${song.notes.length} ${s('个音符 · 字母谱 + 在线跟弹', 'notes · Key letters & guided practice')}</span></span><span class="studio-song-arrow" aria-hidden="true">↗</span></a>`).join('')}</div></section>
<section class="studio-learn"><div><p class="studio-kicker">${s('不用先会，先玩起来', 'NO EXPERIENCE NEEDED')}</p><h2>${s('第一次弹？这就够了。', 'New to piano? Start right here.')}</h2><p>${s('这里的简化旋律适合入门与休闲体验，不等同于完整钢琴编曲，也不能替代真实钢琴的力度与踏板训练。', 'These simplified melodies are for getting started, not full piano arrangements. A virtual keyboard does not replace weighted keys or pedal technique.')}</p></div><div class="studio-help"><details><summary>${s('电脑上怎么弹？', 'How do I play on a computer?')}</summary><p>${s('点击琴键，或按琴键上的大写字母。A 对应 C3，K 对应中央 C（C4），T 对应 C5。数字和部分字母对应黑键。', 'Click a key, or press its large letter. A plays C3, K plays middle C (C4), and T plays C5. Numbers and some letters play the black keys.')}</p></details><details><summary>${s('手机上琴键太多怎么办？', 'How do I play on a phone?')}</summary><p>${s('用琴键下方的左右箭头移动音区。跟弹时，会自动把下一个琴键移到可见区域。横屏有更大的弹奏空间。', 'Use the arrows below the keys to move the range. Guided mode brings the next key into view automatically. Landscape gives you more playing space.')}</p></details><details><summary>${s('没有声音，怎么检查？', 'Why can’t I hear anything?')}</summary><p>${s('先点击一次琴键以允许浏览器播放音频，再检查设备媒体音量、静音模式、蓝牙输出和页面音量。采样加载失败时会使用合成音。', 'Tap a piano key to allow browser audio. Check media volume, silent mode, Bluetooth output and the volume slider. A synthesized tone is used if samples cannot load.')}</p></details><a href="${base}/tutorials.html">${s('去看看入门教程', 'Explore beginner lessons')} →</a></div></section></main><footer class="studio-footer"><span>Piano Online <span class="brand-light">© 2026</span></span><span>${s('给日常，多一点音乐。', 'Make a little room for music.')}</span><a href="${base}/about.html">${s('关于', 'About')}</a></footer></body></html>`;
}

export async function generateStudioPages(root) {
  await mkdir(path.join(root,'en'),{recursive:true});
  for (const locale of ['zh','en']) for (const home of [true,false]) {
    const file = path.join(root, locale==='zh'?'':'en', home?'index.html':'piano.html');
    await writeFile(file,renderStudioPage(locale,home));
  }
  // Apply the shared design to legacy editorial pages without changing their content/hooks.
  for (const name of ['about.html','en/about.html','practice.html']) {
    const file=path.join(root,name); let html=await readFile(file,'utf8');
    if (!html.includes('/css/studio.css')) html=html.replace('</head>',`<link rel="stylesheet" href="/css/studio.css?v=${STUDIO_VERSION}"></head>`);
    html=html.replace(/<nav class="nav-bar">[\s\S]*?<\/nav>/,studioNav(name.startsWith('en/')?'en':'zh','learn'));
    await writeFile(file,html);
  }
}
